language: c

arch:
  - amd64
  - ppc64le

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y git gcc libtool autoconf make

install:
  - autoreconf -fvi
  - ./configure --build=ppc64le-redhat-linux --enable-debug=full
  - make
  - make check
  - sudo make install
